# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

            - name: Sync Maven
  # You may pin to the exact commit or the version.
  # uses: guoshiqiufeng/github-action-sync-maven@bfe2d292ee8ea65912c72eebceaacc05806d23bc
  uses: guoshiqiufeng/github-action-sync-maven@v1.2.2
  with:
    # Repository URL
    repositories: # default is https://repo1.maven.org/maven2/
    # List of dependencies to sync
    dependenciesJson: # default is [{"groupId":"io.github.guoshiqiufeng", "artifactId":"loki", "version":"0.8.1"}]


                      - name: action-maven
  # You may pin to the exact commit or the version.
  # uses: comchangs/action-maven@54db702e085ac767dad94c87e84499afb9d77162
  uses: comchangs/action-maven@v0.4-beta


            - name: Maven version
  # You may pin to the exact commit or the version.
  # uses: JActions/maven-version@1cad7209ce5ea389ae867e5f32bdf5a73b495d64
  uses: JActions/maven-version@v1.2.0
  with:
    # Path to Maven's pom.xml file
    pom: # optional
    # Path to Maven's settings.xml file
    settings: # optional


                - name: Maven Dependency Tree Dependency Submission
  # You may pin to the exact commit or the version.
  # uses: advanced-security/maven-dependency-submission-action@aeab9f885293af501bae8bdfe88c589528ea5e25
  uses: advanced-security/maven-dependency-submission-action@v4.1.2
  with:
    # The directory that contains the maven project
    directory: # optional, default is ${{ github.workspace }}
    # Optional path to a Maven settings.xml file for the dependencies to be resolved
    settings-file: # optional
    # Flag for optionally ignoring any maven wrapper files (mvnw) and instead rely on the PATH provided mvn
    ignore-maven-wrapper: # optional
    # Additional maven arguments to add to the command line invocation of maven when it generates the dependency snapshot
    maven-args: # optional, default is 
    # Optionally include the file name in the dependency snapshot report to GitHub. This is required to be true if you want the results in the dependency tree to have a working link.
    snapshot-include-file-name: # optional, default is true
    # An optional override to specify the path to the file in the repository that the snapshot should be associated with.
    snapshot-dependency-file-name: # optional
    # The GitHub token to use to submit the depedency snapshot to the repository
    token: # optional, default is ${{ github.token }}
    # The SHA that the results will be linked to in the dependency snapshot
    snapshot-sha: # optional, default is 
    # The ref that the results will be linked to in the dependency snapshot
    snapshot-ref: # optional, default is 
    # The name of the detector that generated the dependency snapshot
    detector-name: # optional
    # The version of the detector that generated the dependency snapshot
    detector-version: # optional
    # The URL to the detector that generated the dependency snapshot
    detector-url: # optional
    # An optional identifier to distinguish between multiple dependency snapshots of the same type
    correlator: # optional, default is 

            - name: Java Maven release
  # You may pin to the exact commit or the version.
  # uses: qcastel/github-actions-maven-release@88522b1841bc65c43d7040c15b0ac0867c2fa7ea
  uses: qcastel/github-actions-maven-release@v1.12.31
  with:
    # Filter the branch to execute the release on
    release-branch-name: # optional, default is master
    # Enable gpg signing
    gpg-enabled: # optional
    # The GPG key ID
    gpg-key-id: # optional
    # The GPG key
    gpg-key: # optional
    # The GPG passphrase
    gpg-passphrase: # optional
    # The SSH private key used during the maven release git commit
    ssh-private-key: # optional
    # The SSH passphrase
    ssh-passphrase: # optional
    # The git user name for committing the release
    git-release-bot-name: # optional, default is release-bot
    # The git user email for committing the release
    git-release-bot-email: # optional, default is release-bot@github.com
    # Skip the git fetch and reset executed for safety by this action
    git-skip-sanity-check: # optional, default is false
    # !!DEPRECATED: Use maven-servers instead!! Maven server repository id to push the artifacts to
    maven-repo-server-id: # optional, default is 
    # !!DEPRECATED: Use maven-servers instead!! Maven server repository username
    maven-repo-server-username: # optional, default is 
    # !!DEPRECATED: Use maven-servers instead!! Maven server repository password
    maven-repo-server-password: # optional, default is 
    # The maven server repositories, in a JSON format. Example: [{"id": "serverId1", "username": "username", "password": "password1", "privateKey": "privatekey1", "passphrase": "passphrase1"}, {"id": "serverId2", "username": "username2", "password": "password2"}]
    maven-servers: # optional, default is []
    # The maven arguments for the release
    maven-args: # optional, default is 
    # You may have more than one maven projects inside the repo. This option allows you to specify the folder for which you want to trigger the release
    maven-project-folder: # optional, default is ./
    # The maven options for the release
    maven-options: # optional, default is 
    # If define, this option allows you to define a custom development version number, like ${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}-SNAPSHOT
    maven-development-version-number: # optional, default is 
    # If define, this option allows you to define a custom release version number, like ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.0
    maven-release-version-number: # optional, default is 
    # The ID of your registry. For example, for docker hub, it is `registry.hub.docker.com`
    docker-registry-id: # default is fake
    # The username for your docker registry
    docker-registry-username: # default is fake
    # The password for your docker registry
    docker-registry-password: # default is fake
    # Skip maven release perform
    skip-perform: # optional
    # Increment the major version number
    version-major: # optional
    # Increment the minor version number
    version-minor: # optional
    # M2 home folder
    m2-home-folder: # optional, default is /root/.m2
    # Github access token. https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
    access-token: # optional




                      - name: Creating a maven build
  # You may pin to the exact commit or the version.
  # uses: PrajjawalBanati/Build_Management_Using_Maven@1be3a1523ccf20176dc1ef458bcca0927e303fe3
  uses: PrajjawalBanati/Build_Management_Using_Maven@0.0.1



          


                
          
